/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cm.codebrain.ui.application.backoffice;

import cm.codebrain.ui.application.ModelForm;
import cm.codebrain.ui.application.controller.Dictionnaire;
import cm.codebrain.ui.application.controller.GlobalParameters;
import cm.codebrain.ui.application.enumerations.EnumLibelles;
import static cm.codebrain.ui.application.enumerations.Enums.CREATE;
import java.util.List;

/**
 *
 * @author KSA-INET
 */
public class CategorieForm extends ModelForm {
    
    private final String etablissementLevel = "Etablissement";

    /**
     * Creates new form CategorieForm
     *
     * @param title
     */
    public CategorieForm(String title) {
        super(title, 520, 320);

        this.showActionBar();
        this.setActionMenu(CREATE);
        this.showMenuBar();

//        this.addFormData("userCode", title);
//    addActionSupplementaire(
    }

    @Override
    public void createForm() {

        this.entity = "Categorie";
        initComponents();

    }

    @Override
    public void addActionSupplementaire() {
        super.addActionSupplementaire(); //To change body of generated methods, choose Tools | Templates.

        eventLevelSecurity();
    }

    @Override
    public void actionBtnValider(java.awt.event.ActionEvent evt) {
        super.actionBtnValider(evt);
    }

    private void eventLevelSecurity() {
        String[] fields = {"code", "intitule", "levelsId"};

        String clause = null;

        List args = null;//new ArrayList();

        String[][] parametresGrid = {
            {"code", Dictionnaire.get(EnumLibelles.Business_Libelle_code),
                "2"},
            {"intitule",
                Dictionnaire.get(EnumLibelles.Business_Libelle_Intitule),
                "3"}};

//        if (this.getData("action") != null) {
        addAction(etablissementCodeInput, etablissementLevel, parametresGrid, fields, clause, args, etablissementCodeInput, etablissementIntituleInput);
//        }
    }
    
    @Override
    public void makeModelData(){
        super.makeModelData();
        modelFinal.put(etablissementLevel.toLowerCase()+"Id", GlobalParameters.getVar(etablissementLevel));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel mainPanel = new javax.swing.JPanel();
        javax.swing.JPanel panelContent = new javax.swing.JPanel();
        javax.swing.JPanel panelIdentifiant = new javax.swing.JPanel();
        javax.swing.JLabel labelCode = new javax.swing.JLabel();
        javax.swing.JLabel labelPrenom = new javax.swing.JLabel();
        codeInput = new javax.swing.JTextField();
        intituleInput = new javax.swing.JTextField();
        javax.swing.JPanel panelCategorie = new javax.swing.JPanel();
        javax.swing.JLabel labelLevel = new javax.swing.JLabel();
        etablissementCodeInput = new javax.swing.JTextField();
        etablissementIntituleInput = new javax.swing.JTextField();

        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        panelContent.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        panelIdentifiant.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), Dictionnaire.get(EnumLibelles.Business_Libelle_Identifiant))); // NOI18N
        panelIdentifiant.setOpaque(false);

        labelCode.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_code)); // NOI18N
        labelCode.setName("usernameLabel"); // NOI18N

        labelPrenom.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_Intitule)); // NOI18N
        labelPrenom.setName("usernameLabel"); // NOI18N

        codeInput.setName("codeInput"); // NOI18N
        this.addFormData("code", codeInput);

        intituleInput.setName("intituleInput"); // NOI18N
        this.addFormData("intitule", intituleInput);

        javax.swing.GroupLayout panelIdentifiantLayout = new javax.swing.GroupLayout(panelIdentifiant);
        panelIdentifiant.setLayout(panelIdentifiantLayout);
        panelIdentifiantLayout.setHorizontalGroup(
            panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdentifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelPrenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(labelCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(intituleInput))
                .addContainerGap())
        );
        panelIdentifiantLayout.setVerticalGroup(
            panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdentifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intituleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCategorie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), Dictionnaire.get(EnumLibelles.Business_Libelle_Etablissement))); // NOI18N
        panelCategorie.setOpaque(false);

        labelLevel.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_level)); // NOI18N
        labelLevel.setName("usernameLabel"); // NOI18N

        etablissementCodeInput.setName("etablissementCodeInput"); // NOI18N
        this.addFormData("etablissementId", etablissementCodeInput);

        etablissementIntituleInput.setName("etablissementIntituleInput"); // NOI18N

        javax.swing.GroupLayout panelCategorieLayout = new javax.swing.GroupLayout(panelCategorie);
        panelCategorie.setLayout(panelCategorieLayout);
        panelCategorieLayout.setHorizontalGroup(
            panelCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategorieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etablissementCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etablissementIntituleInput, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCategorieLayout.setVerticalGroup(
            panelCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategorieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etablissementCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etablissementIntituleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codeInput;
    private javax.swing.JTextField etablissementCodeInput;
    private javax.swing.JTextField etablissementIntituleInput;
    private javax.swing.JTextField intituleInput;
    // End of variables declaration//GEN-END:variables

}
