/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cm.codebrain.ui.application.frontoffice;

import cm.codebrain.ui.application.ModelForm;
import cm.codebrain.ui.application.controller.Dictionnaire;
import cm.codebrain.ui.application.controller.FormParameters;
import cm.codebrain.ui.application.enumerations.EnumLibelles;
import static cm.codebrain.ui.application.enumerations.EnumVariable.CREATE;
import java.util.HashMap;

/**
 *
 * @author KSA-INET
 */
public class EnseignantForm extends ModelForm {

    private final String entityProfession = "Profession";

    /**
     * Creates new form UserForm
     *
     * @param title
     */
    public EnseignantForm(String title){
//            , int width, int height, boolean hideActionMenuTitle, boolean confirmExit) {
        super(title, 960, 530, false, true);

        this.showActionBar();
        etatAction = CREATE;
        this.showMenuBar();

//        this.addFormData("userCode", title);
//    addActionSupplementaire(
    }

    public void createForm() {
        this.entity = "Enseignant";

        initComponents();
        
        setAllComponents(matriculeInput, nameInput, lastNameInput, birthdayInput, bornLocationInput, cniInput, dateDelivranceInput, dateExpirationInput, professionInput, professionIntituleInput);
    }

    protected void addActionSupplementaire() {
        eventProfession();
    }

    private void eventProfession() {

        HashMap[] args = null;

        String[][] parametresGrid = {
            {"code", Dictionnaire.get(EnumLibelles.Business_Libelle_code)},
            {"intitule",
                Dictionnaire.get(EnumLibelles.Business_Libelle_Intitule)}};

        addAction(professionInput, entityProfession, entityProfession.toLowerCase()+"Id", parametresGrid, null, args, professionInput, professionIntituleInput);
    }

    @Override
    protected void eventActionRef() {
        
        String[][] parametresGrid = {
            {"matricule", Dictionnaire.get(EnumLibelles.Business_Libelle_Matricule)},
            {"firstName",
                Dictionnaire.get(EnumLibelles.Business_Libelle_nom)},
            {"lastName",
                Dictionnaire.get(EnumLibelles.Business_Libelle_prenom)}};

        addAction(matriculeInput, entity, entity.toLowerCase()+"Id", parametresGrid, null, null, matriculeInput);
    }

    @Override
    public void makeModelData() {

        super.makeModelData();
        if(masculinRadioButton.isSelected())modelFinal.put("sexe", masculinRadioButton.getActionCommand());
        else if(femininRadioButton.isSelected())modelFinal.put("sexe", femininRadioButton.getActionCommand());
        
        modelFinal.put(entityProfession.toLowerCase()+"Id", FormParameters.get(entityProfession.toLowerCase()+"Id"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexeButtonGroup = new javax.swing.ButtonGroup();
        javax.swing.JPanel mainPanel = new javax.swing.JPanel();
        javax.swing.JPanel panelContent = new javax.swing.JPanel();
        javax.swing.JPanel panelIdentifiant = new javax.swing.JPanel();
        javax.swing.JLabel labelMatricule = new javax.swing.JLabel();
        matriculeInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        javax.swing.JLabel labelfirstName = new javax.swing.JLabel();
        javax.swing.JLabel labelLastName = new javax.swing.JLabel();
        javax.swing.JLabel labelbornLocation = new javax.swing.JLabel();
        javax.swing.JLabel labelMatricule4 = new javax.swing.JLabel();
        bornLocationInput = new javax.swing.JTextField();
        javax.swing.JLabel labelSexe = new javax.swing.JLabel();
        femininRadioButton = new javax.swing.JRadioButton();
        masculinRadioButton = new javax.swing.JRadioButton();
        birthdayInput = new javax.swing.JFormattedTextField();
        javax.swing.JLabel labelMatricule5 = new javax.swing.JLabel();
        cniInput = new javax.swing.JTextField();
        javax.swing.JLabel labelDateDelivrance = new javax.swing.JLabel();
        dateDelivranceInput = new javax.swing.JFormattedTextField();
        dateExpirationInput = new javax.swing.JFormattedTextField();
        javax.swing.JLabel labelDateExpiration = new javax.swing.JLabel();
        javax.swing.JPanel panelProfil = new javax.swing.JPanel();
        chooseButton = new javax.swing.JButton();
        javax.swing.JPanel panelImage = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        javax.swing.JLabel labelImage = new javax.swing.JLabel();
        javax.swing.JPanel panelSalle = new javax.swing.JPanel();
        javax.swing.JLabel labelProfession = new javax.swing.JLabel();
        professionInput = new javax.swing.JTextField();
        professionIntituleInput = new javax.swing.JTextField();

        setRadiBottun(sexeButtonGroup, masculinRadioButton, femininRadioButton);
        fieldSearch("sexe", sexeButtonGroup);
        this.addFormData("sexe", sexeButtonGroup);

        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        panelContent.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        panelIdentifiant.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), Dictionnaire.get(EnumLibelles.Business_Libelle_Identifiant))); // NOI18N
        panelIdentifiant.setOpaque(false);

        labelMatricule.setLabelFor(matriculeInput);
        labelMatricule.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_Matricule, true)); // NOI18N
        labelMatricule.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelMatricule.setName("usernameLabel"); // NOI18N

        matriculeInput.setName("matriculeInput"); // NOI18N
        this.addFormData("matricule", matriculeInput);
        this.setRef(matriculeInput);
        fieldSearch("matricule", matriculeInput);
        fieldsRequired.add(matriculeInput);

        nameInput.setName("matriculeInput"); // NOI18N
        this.addFormData("firstName", nameInput);
        fieldSearch("firstName", nameInput);
        fieldsRequired.add(nameInput);

        lastNameInput.setName("matriculeInput"); // NOI18N
        this.addFormData("lastName", lastNameInput);
        fieldSearch("lastName", lastNameInput);

        labelfirstName.setLabelFor(nameInput);
        labelfirstName.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_nom, true)); // NOI18N
        labelfirstName.setName("usernameLabel"); // NOI18N

        labelLastName.setLabelFor(lastNameInput);
        labelLastName.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_prenom)); // NOI18N
        labelLastName.setName("usernameLabel"); // NOI18N

        labelbornLocation.setLabelFor(bornLocationInput);
        labelbornLocation.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_BornLocation, true)); // NOI18N
        labelbornLocation.setName("usernameLabel"); // NOI18N

        labelMatricule4.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_BirthDay, true)); // NOI18N
        labelMatricule4.setName("usernameLabel"); // NOI18N

        bornLocationInput.setName("matriculeInput"); // NOI18N
        bornLocationInput.setPreferredSize(new java.awt.Dimension(199, 28));
        this.addFormData("bornLocation", bornLocationInput);
        fieldSearch("bornLocation", bornLocationInput);
        fieldsRequired.add(bornLocationInput);

        labelSexe.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_Sexe, true)); // NOI18N
        labelSexe.setName("usernameLabel"); // NOI18N

        sexeButtonGroup.add(femininRadioButton);
        femininRadioButton.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_Feminin)); // NOI18N
        femininRadioButton.setActionCommand(EnumLibelles.Business_Libelle_Feminin.toString()); // NOI18N

        sexeButtonGroup.add(masculinRadioButton);
        masculinRadioButton.setSelected(true);
        masculinRadioButton.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_Masculin)); // NOI18N
        masculinRadioButton.setActionCommand(EnumLibelles.Business_Libelle_Masculin.toString()); // NOI18N

        birthdayInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        birthdayInput.setName("birthday"); // NOI18N
        this.addFormData("birthday", birthdayInput);
        fieldSearch("birthday", birthdayInput);
        fieldsRequired.add(birthdayInput);

        labelMatricule5.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_cni, true)); // NOI18N
        labelMatricule5.setName("usernameLabel"); // NOI18N

        cniInput.setName("matriculeInput"); // NOI18N
        this.addFormData("cni", cniInput);
        fieldSearch("cni", cniInput);
        fieldsRequired.add(cniInput);

        labelDateDelivrance.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_DateDelivrance, true)); // NOI18N
        labelDateDelivrance.setName("usernameLabel"); // NOI18N

        dateDelivranceInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        dateDelivranceInput.setName("birthday"); // NOI18N
        this.addFormData("dateDelivrance", dateDelivranceInput);
        fieldSearch("dateDelivrance", dateDelivranceInput);
        fieldsRequired.add(dateDelivranceInput);

        dateExpirationInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        dateExpirationInput.setName("birthday"); // NOI18N
        this.addFormData("dateExpire", dateExpirationInput);
        fieldSearch("dateExpire", dateExpirationInput);
        fieldsRequired.add(dateExpirationInput);

        labelDateExpiration.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_DateExpiration, true)); // NOI18N
        labelDateExpiration.setName("usernameLabel"); // NOI18N

        javax.swing.GroupLayout panelIdentifiantLayout = new javax.swing.GroupLayout(panelIdentifiant);
        panelIdentifiant.setLayout(panelIdentifiantLayout);
        panelIdentifiantLayout.setHorizontalGroup(
            panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdentifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIdentifiantLayout.createSequentialGroup()
                        .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelIdentifiantLayout.createSequentialGroup()
                                .addComponent(labelMatricule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(matriculeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelfirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(nameInput, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIdentifiantLayout.createSequentialGroup()
                                .addComponent(labelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelIdentifiantLayout.createSequentialGroup()
                                .addComponent(lastNameInput)
                                .addGap(12, 12, 12))))
                    .addGroup(panelIdentifiantLayout.createSequentialGroup()
                        .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelIdentifiantLayout.createSequentialGroup()
                                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelIdentifiantLayout.createSequentialGroup()
                                        .addComponent(labelMatricule5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cniInput, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelIdentifiantLayout.createSequentialGroup()
                                        .addComponent(labelDateDelivrance, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dateDelivranceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(labelDateExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dateExpirationInput))
                            .addGroup(panelIdentifiantLayout.createSequentialGroup()
                                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMatricule4)
                                    .addComponent(labelSexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelIdentifiantLayout.createSequentialGroup()
                                        .addComponent(masculinRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(femininRadioButton))
                                    .addGroup(panelIdentifiantLayout.createSequentialGroup()
                                        .addComponent(birthdayInput, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelbornLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bornLocationInput, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(13, 13, 13))))
        );
        panelIdentifiantLayout.setVerticalGroup(
            panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdentifiantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matriculeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelbornLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bornLocationInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMatricule4)
                        .addComponent(birthdayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(femininRadioButton)
                    .addComponent(masculinRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricule5)
                    .addComponent(cniInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelIdentifiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateDelivranceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDateExpiration)
                        .addComponent(dateExpirationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelDateDelivrance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        panelProfil.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), Dictionnaire.get(EnumLibelles.Business_Libelle_Profil))); // NOI18N
        panelProfil.setVisible(false);
        panelProfil.setLayout(new java.awt.BorderLayout());

        chooseButton.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_Choose)); // NOI18N
        panelProfil.add(chooseButton, java.awt.BorderLayout.SOUTH);

        panelImage.setLayout(new javax.swing.OverlayLayout(panelImage));

        imageLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        imageLabel.setMaximumSize(new java.awt.Dimension(140, 140));
        imageLabel.setMinimumSize(new java.awt.Dimension(140, 140));
        imageLabel.setPreferredSize(new java.awt.Dimension(135, 135));
        panelImage.add(imageLabel);

        labelImage.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImage.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_Image)); // NOI18N
        labelImage.setMaximumSize(new java.awt.Dimension(141, 166));
        labelImage.setPreferredSize(new java.awt.Dimension(135, 135));
        panelImage.add(labelImage);

        panelProfil.add(panelImage, java.awt.BorderLayout.CENTER);

        panelSalle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), Dictionnaire.get(EnumLibelles.Business_Libelle_Profession))); // NOI18N
        panelSalle.setOpaque(false);

        labelProfession.setLabelFor(professionInput);
        labelProfession.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_level, true)); // NOI18N
        labelProfession.setName("usernameLabel"); // NOI18N

        professionInput.setName("code"); // NOI18N
        this.addFormData("professionId", professionInput);
        fieldSearch("Profession->professionId->code", professionInput);
        fieldsRequired.add(professionInput);

        professionIntituleInput.setEditable(false);
        professionIntituleInput.setFocusable(false);
        professionIntituleInput.setName("intitule"); // NOI18N
        fieldSearch("Profession->professionId->intitule", professionIntituleInput);

        javax.swing.GroupLayout panelSalleLayout = new javax.swing.GroupLayout(panelSalle);
        panelSalle.setLayout(panelSalleLayout);
        panelSalleLayout.setHorizontalGroup(
            panelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProfession, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(professionInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(professionIntituleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSalleLayout.setVerticalGroup(
            panelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProfession, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(professionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(professionIntituleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelSalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelProfil.getAccessibleContext().setAccessibleName("Classe");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField birthdayInput;
    private javax.swing.JTextField bornLocationInput;
    private javax.swing.JButton chooseButton;
    private javax.swing.JTextField cniInput;
    private javax.swing.JFormattedTextField dateDelivranceInput;
    private javax.swing.JFormattedTextField dateExpirationInput;
    private javax.swing.JRadioButton femininRadioButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JRadioButton masculinRadioButton;
    private javax.swing.JTextField matriculeInput;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField professionInput;
    private javax.swing.JTextField professionIntituleInput;
    private javax.swing.ButtonGroup sexeButtonGroup;
    // End of variables declaration//GEN-END:variables

}
