/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cm.codebrain.ui.application.administration;

import cm.codebrain.ui.application.ModelForm;
import cm.codebrain.ui.application.controller.Dictionnaire;
import cm.codebrain.ui.application.controller.FormParameters;
import cm.codebrain.ui.application.enumerations.EnumLibelles;
import static cm.codebrain.ui.application.enumerations.EnumVariable.MODIF;
import java.util.HashMap;

/**
 *
 * @author KSA-INET
 */
public class ParametreAnneeAcademiqueForm extends ModelForm {
    
    private final String entityAnneeAcademic = "AnneeAcademic";

    /**
     * Creates new form CategorieForm
     *
     * @param title
     */
    public ParametreAnneeAcademiqueForm(String title) {
        super(title, 520, 320);

        this.showActionBar();
        etatAction = MODIF;
        this.showMenuBar();

//        this.addFormData("userCode", title);
//    addActionSupplementaire(
    }

    @Override
    public void createForm() {

        this.entity = "Etablissement";
        initComponents();
        setAllComponents(nomAbregeInput, nomCompletInput);
    }

    @Override
    public void addActionSupplementaire() {
        super.addActionSupplementaire(); //To change body of generated methods, choose Tools | Templates.

        eventAnneeAcademic();
    }

    @Override
    public void makeModelData(){
        super.makeModelData();
        modelFinal.put("session", FormParameters.get("session"));

    }

    @Override
    protected void eventActionRef() {

        String[][] parametresGrid = {
            {"nameAbrege", Dictionnaire.get(EnumLibelles.Business_Libelle_Nom_Abrege)},
            {"fullName",
                Dictionnaire.get(EnumLibelles.Business_Libelle_Nom_Complet)}};

        addAction(nomAbregeInput, entity, entity.toLowerCase()+"Id", parametresGrid, null, null, nomAbregeInput, nomCompletInput);
    }
    
    private void eventAnneeAcademic() {

        HashMap[] args = null;

        String[][] parametresGrid = {
            {"session", Dictionnaire.get(EnumLibelles.Business_Libelle_Session)},
            {"dateOuverture",
                Dictionnaire.get(EnumLibelles.Business_Libelle_DateDebut)},
            {"dateFermeture",
                Dictionnaire.get(EnumLibelles.Business_Libelle_DateFin)}};

        addAction(sessionInput, entityAnneeAcademic, "session", parametresGrid, null, args, sessionInput);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel mainPanel = new javax.swing.JPanel();
        javax.swing.JPanel panelContent = new javax.swing.JPanel();
        javax.swing.JPanel panelCategorie = new javax.swing.JPanel();
        javax.swing.JLabel labelLevel = new javax.swing.JLabel();
        nomAbregeInput = new javax.swing.JTextField();
        nomCompletInput = new javax.swing.JTextField();
        javax.swing.JLabel labelLevel1 = new javax.swing.JLabel();
        sessionInput = new javax.swing.JTextField();

        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        panelContent.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        panelCategorie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), Dictionnaire.get(EnumLibelles.Business_Libelle_Etablissement))); // NOI18N
        panelCategorie.setOpaque(false);

        labelLevel.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_level, true)); // NOI18N
        labelLevel.setName("usernameLabel"); // NOI18N

        nomAbregeInput.setName("nameAbrege"); // NOI18N
        this.addFormData("etablissementId", nomAbregeInput);
        fieldSearch("nameAbrege", nomAbregeInput);
        fieldsRequired.add(nomAbregeInput);

        nomCompletInput.setName("fullName"); // NOI18N
        fieldSearch("fullName", nomCompletInput);

        javax.swing.GroupLayout panelCategorieLayout = new javax.swing.GroupLayout(panelCategorie);
        panelCategorie.setLayout(panelCategorieLayout);
        panelCategorieLayout.setHorizontalGroup(
            panelCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategorieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomAbregeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomCompletInput, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCategorieLayout.setVerticalGroup(
            panelCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategorieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomAbregeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomCompletInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelLevel1.setText(Dictionnaire.get(EnumLibelles.Business_Libelle_AnneeAcademique)); // NOI18N
        labelLevel1.setName("usernameLabel"); // NOI18N

        sessionInput.setName("nameAbrege"); // NOI18N
        this.addFormData("anneeAcademic", sessionInput);
        fieldSearch("session", sessionInput);
        fieldsRequired.add(sessionInput);

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addComponent(labelLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sessionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField nomAbregeInput;
    private javax.swing.JTextField nomCompletInput;
    private javax.swing.JTextField sessionInput;
    // End of variables declaration//GEN-END:variables

}
